name: Sync Actions

# permissions:
#   id-token: write
#   contents: write
#   checks: write
#   issues: write
#   pull-requests: write

on:
  # push: 
  #   branches: [ main ]
  #   paths:
  #     - '.github/workflows/**'
  workflow_dispatch:
  
   

jobs:
  replicate:
    runs-on: ubuntu-latest
   
    steps:
      - name: Validate Token
        run: |
          echo "Validating token access..."
          # Test basic API access
          curl -f -H "Authorization: token ${{ secrets.MULTI_ACCESS_TOKEN }}" \
               "https://api.github.com/user" || exit 1
          
          # Test org access  
          curl -f -H "Authorization: token ${{ secrets.MULTI_ACCESS_TOKEN }}" \
               "https://api.github.com/user/orgs" || exit 1
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Push Action to repos
        uses: derberg/manage-files-in-multiple-repositories@v2
   
        with:
          github_token: ${{ secrets.MULTI_ACCESS_TOKEN }} # PAT mit Schreibrechten auf alle Ziel-Repos
          patterns_to_include: .github/workflows/MarkAndCloseStaleIssuesPush.yml
          patterns_to_ignore: .github/workflows/SyncActions.yml
          # topics_to_include: icinga
          # destination: '.github/workflows'
          committer_username: Sync-Action
          commit_message: "ci: update workflow action for stale issues"
          
